~=chdir /D %USERPROFILE%
cd=chdir /D $1
clear=cls
fn=dir $1 /S /B
gd=git diff
gl=git log
gu=git up
gs=git status
gf=git fetch
gr=git remote -v
gp=git push
gpl=git pull
gc=git commit
gco=git checkout
ga=git add .
ls=dir /W & echo. && echo               Steve Ballmer says: "It's 'dir', not 'ls', you hippie!"
subl="C:\Program Files\Sublime Text 2\sublime_text.exe" $1
x=exit